GET http://localhost:3000/api/profiles/other
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiR2lueXUiLCJpYXQiOjE3MzUzMjMyMDgsImV4cCI6MTczNTMyNjgwOH0.Pal4QOJYvoiQUSX90EVh7YQokOi5REShqPntbLXtNW8
