GET http://localhost:3000/api/conversations/specific/Piccolo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInVzZXJuYW1lIjoiR2lueXUiLCJpYXQiOjE3MzU0NTI5MTQsImV4cCI6MTczNTQ1NjUxNH0.VUlLoMJTD9Q4R2vXE-OcyacWi7yF-kGh8KEjdkmfmck
